version: 2
updates:
  # Keep GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep Python dependencies (requirements.txt and requirements_test.txt) up-to-date
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
